### ISSUE TITLE
Error on Py3 to fix whitespaces

### ISSUE THREAD

**Issue by fabioz** [ESSS/esss_fix_format#19]
Found this error on Py3:

Traceback (most recent call last):
  File "W:\rocky40\envs\petrolib20-py36\Scripts\ff-script.py", line 5, in <module>
    sys.exit(esss_fix_format.cli.main())
  File "W:\rocky40\envs\petrolib20-py36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "W:\rocky40\envs\petrolib20-py36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "W:\rocky40\envs\petrolib20-py36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\rocky40\envs\petrolib20-py36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "W:\rocky40\envs\petrolib20-py36\lib\site-packages\esss_fix_format\cli.py", line 128, in main
    new_contents = fix_whitespace(new_contents.splitlines(True), eol, ends_with_eol)
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by fabioz** [comment]
Note: happened because `sorter.output` is None.

**Comment by prusse-martin** [comment]
Are you using version 1.4.1?
