### ISSUE TITLE
ff -c is not showing the filename that were processing when it crash

### ISSUE THREAD

**Issue by alexandrebbruno** [ESSS/esss_fix_format#46]
I was ruing ff -c in a group of files which there was a file that were crashing the ff because it had some especial characters. It had been extremely difficult to find the source of this problem because the ff -c was not showing the filename that had the problem. So, I think that would be nice if the ff -c shows the filename that were processing right before the crash.

Here is the current way:

```
ff -c 
Running black on 1 files...
All done! ✨✨ �� ✨✨
1 file left unchanged.
Traceback (most recent call last):
  File "W:\release\envs\souring20-py36\Scripts\ff-script.py", line 9, in <module>
    sys.exit(main())
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 218, in main
    return _main(files_or_directories, check, stdin, commit, format_code, verbose=verbose)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 445, in _main
    verbose=verbose)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 242, in _process_file
    content = content_bytes.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 7437: invalid continuation byte
```

Here is the way that I think it would be better:

```
ff -c
Running black on 1 files...
All done! ✨✨ �� ✨✨
1 file left unchanged.
**Error while processing file: W:\release\Projects\souring\steam_souring10calc\source\c++\geochemical\reaktoro_calculator\ReaktoroVertexCalculator.cpp**
Traceback (most recent call last):
  File "W:\release\envs\souring20-py36\Scripts\ff-script.py", line 9, in <module>
    sys.exit(main())
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\release\envs\souring20-py36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 218, in main
    return _main(files_or_directories, check, stdin, commit, format_code, verbose=verbose)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 449, in _main
    verbose=verbose)
  File "W:\release\envs\souring20-py36\lib\site-packages\esss_fix_format\cli.py", line 242, in _process_file
    content = content_bytes.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 7437: invalid continuation byte
```

**Comment by prusse-martin** [comment]
Yes, give the offending file is essential.
I also think the handling the `UnicodeDecodeError` reporting the error and proce3ding to the next file will be nice.

**Comment by prusse-martin** [comment]
```
