### ISSUE TITLE
Module 'isort.settings' has no attribute 'from_path'

### ISSUE THREAD

**Issue by gcardozo123** [ESSS/esss_fix_format#52]
```
>>> ff -c
Running black on 3 files...
All done! ✨ � ✨
3 files left unchanged.
Traceback (most recent call last):
  File "W:\Miniconda3\envs\cg_playground-py36\Scripts\ff-script.py", line 9, in <module>
    sys.exit(main())
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 218, in main
    return _main(files_or_directories, check, stdin, commit, format_code, verbose=verbose)
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 451, in _main
    changed, new_errors, formatter = _process_file(filename, check, pydevf_format_func,
  File "W:\Miniconda3\envs\cg_playground-py36\lib\site-packages\esss_fix_format\cli.py", line 316, in _process_file
    settings_loaded = isort.settings.from_path(settings_path)
AttributeError: module 'isort.settings' has no attribute 'from_path'
```
We should either conform to the current `isort` version or update `isort` version on `environment.devenv.yml` to 
`isort>=4.3.4, <5.0`

**Comment by nicoddemus** [comment]
We should upgrade, it seems like a simple fix. 👍
